# Generated by Django 5.2.4 on 2026-03-23 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scramblesession',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_scramble_session_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submitedquestions',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_submitted_questions_school', to='school.school'),
        ),
        migrations.AddField(
            model_name='submitedquestions',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_submitted_questions_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
