# Generated by Django 5.2.4 on 2026-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_logo_fileId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
