"""
Django settings for estudiebuddie_backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url, os
from dotenv import load_dotenv
load_dotenv()

# import sqlite3
# from decimal import Decimal, InvalidOperation

# def safe_decimal(value):
#     if value is None:
#         return None
#     try:
#         return Decimal(str(value)).quantize(Decimal("0.0001"))
#     except (InvalidOperation, TypeError, ValueError):
#         return None

# sqlite3.register_converter("NUMERIC", safe_decimal)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DATABASE_URL = os.getenv("DATABASE_URL")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m#yo8x92w6537bjl9v2z1iqqn==drfoqzo%tyi@=fn(ci!+h+q'

# SECURITY WARNING: don't run with debug turned on in production!

# DEBUG = True
DEBUG = False if DATABASE_URL else True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'estudiebuddieremake.pythonanywhere.com',
    "api.classicbrownline.com",
    ".fly.dev",
    "estudiebuddie-backend.fly.dev",
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'school',		# <- added startapp here
    'user',		# <- added startapp here
    'auth_app',		# <- added startapp here
    'shufflequestions',		# <- added startapp here
    'defaultpage',		# <- added startapp here
    'contribute',		# <- added startapp here
    'take_quiz',		# <- added startapp here
    'django_extensions',		# <- added django_extensions here
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',  # For cross-origin requests
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Middleware for CORS
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", # whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'estudiebuddie_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'estudiebuddie_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

if DATABASE_URL:
    # Fly.io / Neon Postgres
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    # Local dev → SQLite
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
# This is where collectstatic will put all files
STATIC_ROOT = BASE_DIR / 'static' # this should be auto created (deployment only) in startproject command

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'

# # Allow requests from your React frontend
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000", # React dev server
    "http://localhost:3000",  # React dev server
    "http://localhost:3001",
    "http://localhost:3002",
    "https://dafetiteogaga.github.io",  # If deployed
    "https://estudiebuddie-frontend.pages.dev", # cloudflare
]
# CORS_ALLOW_ALL_ORIGINS = True # Allow all origins for development purposes
CSRF_TRUSTED_ORIGINS = [
    'https://estudiebuddie-backend.fly.dev',
    'https://estudiebuddie-frontend.pages.dev',
]
# allwed headers
CORS_EXPOSE_HEADERS = [
    "Content-Disposition",
    "Content-Length",
]

IMAGEKIT_PRIVATE_KEY = os.getenv("IMAGEKIT_PRIVATE_KEY")
# if not IMAGEKIT_PRIVATE_KEY:
#     raise Exception("IMAGEKIT_PRIVATE_KEY is missing")
IMAGEKIT_PUBLIC_KEY = os.getenv("IMAGEKIT_PUBLIC_KEY")
# if not IMAGEKIT_PUBLIC_KEY:
#     raise Exception("IMAGEKIT_PUBLIC_KEY is missing")
IMAGEKIT_URL_ENDPOINT = os.getenv("IMAGEKIT_URL_ENDPOINT")
# if not IMAGEKIT_URL_ENDPOINT:
#     raise Exception("IMAGEKIT_URL_ENDPOINT is missing")

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": ( # tells DRF how to handle authentication (i.e use JWTAuthentication)
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': [ # default permission for all views (but overridden in individual views)
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    # 'EXCEPTION_HANDLER': 'custom_permissions.permissions.custom_exception_handler',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24), # timedelta(minutes=15),   # default 5, now 15 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),     # default 1, now 14 days
    "ROTATE_REFRESH_TOKENS": True,                   # issue a new refresh each time
    "BLACKLIST_AFTER_ROTATION": True,                # block old refresh after rotation
}

# CACHES = {
# 	'default': {
# 		'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
# 		'LOCATION': 'unique-snowflake',
#         'TIMEOUT': None,  # Cache never expires unless explicitly set per view
# 	}
# }

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {name} - {message}",
            "style": "{",
        },
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            # "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console"],
        "level": "INFO",  # allows frm the least
    },

    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}