# Generated by Django 5.2.4 on 2025-12-27 02:56

import contribute.utils.hooks
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.CharField(max_length=100)),
                ('class_category', models.CharField(max_length=100)),
                ('subject_category', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('type_category', 'class_category', 'subject_category')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fileId', models.CharField(blank=True, max_length=225, null=True)),
                ('options', models.JSONField(validators=[contribute.utils.hooks.validate_question_options])),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='contribute.category')),
            ],
        ),
    ]
