# Generated by Django 5.2.4 on 2026-03-23 06:46

import contribute.utils.hooks
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_category', models.CharField(max_length=100)),
                ('class_category', models.CharField(max_length=100)),
                ('subject_category', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('type_category', 'class_category', 'subject_category')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fileId', models.CharField(blank=True, max_length=225, null=True)),
                ('options', models.JSONField(validators=[contribute.utils.hooks.validate_question_options])),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_questions', to='contribute.category')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_duration', models.FloatField(blank=True, null=True)),
                ('selected_option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_question_answers', to='contribute.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=contribute.utils.hooks.generate_unique_id, max_length=100, unique=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='rn_quiz_sessions', to='contribute.question')),
            ],
        ),
    ]
