# Generated by Django 5.2.4 on 2025-12-29 23:48

import contribute.utils.hooks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0003_alter_question_explanation_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=contribute.utils.hooks.generate_unique_id, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(related_name='quiz_sessions', to='contribute.question')),
            ],
        ),
    ]
