# Generated by Django 5.2.4 on 2025-12-31 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0004_quizsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_questions', to='contribute.category'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='questions',
            field=models.ManyToManyField(related_name='rn_quiz_sessions', to='contribute.question'),
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_question_answers', to='contribute.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_session_answers', to='contribute.quizsession')),
            ],
        ),
    ]
