# Generated by Django 5.2.4 on 2025-12-31 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0005_alter_question_category_alter_quizsession_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
