# Generated by Django 5.2.4 on 2026-01-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0007_quizsession_started_at_quizsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='response_duration',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
