# Generated by Django 5.2.4 on 2026-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(default='blue', max_length=30),
        ),
    ]
