# Generated by Django 5.2.4 on 2026-01-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
