# Generated by Django 5.2.4 on 2026-01-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avater',
            new_name='avatar_code',
        ),
    ]
