# Generated by Django 5.2.4 on 2026-01-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_avater_user_avatar_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributor',
            field=models.BooleanField(default=False),
        ),
    ]
